name: "schoolapi"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    restart: always
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: adminuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: colegio2023
    secrets:
      - db_root_password
      - db_password
    ports:
      - "3306:${MYSQL_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u $$(MYSQL_USER) --password=`cat
          $$(MYSQL_ROOT_PASSWORD_FILE)`",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 3s
  api:
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      APPNAME: QRSChool
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      SERVING_PORT: ${SERVING_PORT}
      ECHO: false
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: adminuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: colegio2023
      JWT_SECRET_KEY_FILE: /run/secrets/jwt_password
      GUNICORN_PROCESSES: 2
      GUNICORN_THREADS: 4
      GUNICORN_TIMEOUT: 120
      FLASK_CONFIG: ${FLASK_CONFIG}
    secrets:
      - db_root_password
      - db_password
      - jwt_password
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home
    ports:
      - "8081:${SERVING_PORT}"
    restart: always
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  jwt_password:
    file: ./secrets/jwt_password.txt
volumes:
  db_data:
  cache: {}
