"""empty message

Revision ID: 236537e82b68
Revises: 9b5e15a6b94f
Create Date: 2024-09-10 06:07:35.346572

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "236537e82b68"
down_revision = "9b5e15a6b94f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("photourl", sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("photourl")

    # ### end Alembic commands ###
