"""empty message

Revision ID: 3affa380256e
Revises:
Create Date: 2024-07-25 06:23:45.623629

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3affa380256e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asistencia",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grupoetnico",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grupo", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matricula",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anio", sa.Integer(), nullable=False),
        sa.Column("periodo", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "module",
        sa.Column("modulename", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("modulename"),
    )
    op.create_table(
        "perfil",
        sa.Column(
            "nombreperfil",
            sa.Enum(
                "SIN",
                "ESTUDIANTE",
                "DOCENTE",
                "ACUDIENTE",
                "ADMINISTRADOR",
                name="perfilschool",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nombreperfil"),
    )
    op.create_table(
        "grado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("cupomaximo", sa.Integer(), nullable=False),
        sa.Column("matricula_id", sa.Integer(), nullable=False),
        sa.Column("comentariomatricula", sa.String(length=1200), nullable=False),
        sa.ForeignKeyConstraint(
            ["matricula_id"],
            ["matricula.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "perfilmodulolnk",
        sa.Column(
            "perfil_id",
            sa.Enum(
                "SIN",
                "ESTUDIANTE",
                "DOCENTE",
                "ACUDIENTE",
                "ADMINISTRADOR",
                name="perfilschool",
            ),
            nullable=False,
        ),
        sa.Column("modulo_id", sa.String(length=200), nullable=False),
        sa.Column("has_permision", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["modulo_id"],
            ["module.modulename"],
        ),
        sa.ForeignKeyConstraint(
            ["perfil_id"],
            ["perfil.nombreperfil"],
        ),
        sa.PrimaryKeyConstraint("perfil_id", "modulo_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("nombres", sa.String(length=255), nullable=False),
        sa.Column("apellidos", sa.String(length=255), nullable=False),
        sa.Column("numeroidentificacion", sa.String(length=255), nullable=False),
        sa.Column("fechaNacimiento", sa.Date(), nullable=False),
        sa.Column("rh", sa.String(length=3), nullable=False),
        sa.Column("telefonoContacto", sa.String(length=15), nullable=True),
        sa.Column("correo", sa.String(length=100), nullable=True),
        sa.Column(
            "perfil_nombre",
            sa.Enum(
                "SIN",
                "ESTUDIANTE",
                "DOCENTE",
                "ACUDIENTE",
                "ADMINISTRADOR",
                name="perfilschool",
            ),
            nullable=True,
        ),
        sa.Column("grado_id", sa.Integer(), nullable=True),
        sa.Column("direccion", sa.String(length=500), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=False),
        sa.Column("grupoetnico_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grupoetnico_id"],
            ["grupoetnico.id"],
        ),
        sa.ForeignKeyConstraint(
            ["perfil_nombre"],
            ["perfil.nombreperfil"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correo"),
    )
    op.create_table(
        "asignatura",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("grado_id", sa.Integer(), nullable=False),
        sa.Column("docente_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["docente_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grado_id"],
            ["grado.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ausentismo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("userausente_id", sa.Integer(), nullable=False),
        sa.Column("responsableRegistro", sa.String(length=200), nullable=False),
        sa.Column("comentario", sa.String(length=1200), nullable=False),
        sa.ForeignKeyConstraint(
            ["userausente_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("hash", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("usuario_id"),
    )
    op.create_table(
        "calendario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("Desripcion", sa.String(length=1200), nullable=True),
        sa.Column("propietario_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["propietario_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("resultado", sa.Integer(), nullable=False),
        sa.Column("comentario", sa.String(length=800), nullable=False),
        sa.Column("aprobado", sa.Boolean(), nullable=False),
        sa.Column("periodo", sa.Integer(), nullable=False),
        sa.Column("evaluado_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluado_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qr",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("code", sa.String(length=55), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userasistencia",
        sa.Column("asistencia_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asistencia_id"],
            ["asistencia.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("asistencia_id", "user_id"),
    )
    op.create_table(
        "evento",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("fechaHora", sa.Date(), nullable=False),
        sa.Column("invitados", sa.String(length=1200), nullable=False),
        sa.Column("ubicacion", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=1200), nullable=False),
        sa.Column("calendario_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendario_id"],
            ["calendario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "horario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diasemana", sa.Integer(), nullable=False),
        sa.Column("horaInicio", sa.Integer(), nullable=False),
        sa.Column("minutoInicio", sa.Integer(), nullable=False),
        sa.Column("horaFinal", sa.Integer(), nullable=False),
        sa.Column("minutoFinal", sa.Integer(), nullable=False),
        sa.Column("asignatura_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asignatura_id"],
            ["asignatura.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notificacioneventos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tiempoantes", sa.Integer(), nullable=False),
        sa.Column("lineatiempo", sa.String(length=50), nullable=False),
        sa.Column("evento_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["evento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notificacioneventos")
    op.drop_table("horario")
    op.drop_table("evento")
    op.drop_table("userasistencia")
    op.drop_table("qr")
    op.drop_table("evaluacion")
    op.drop_table("calendario")
    op.drop_table("auth")
    op.drop_table("ausentismo")
    op.drop_table("asignatura")
    op.drop_table("user")
    op.drop_table("perfilmodulolnk")
    op.drop_table("grado")
    op.drop_table("perfil")
    op.drop_table("module")
    op.drop_table("matricula")
    op.drop_table("grupoetnico")
    op.drop_table("asistencia")
    # ### end Alembic commands ###
