"""empty message

Revision ID: 5736f461d59c
Revises:
Create Date: 2023-09-25 18:47:39.526267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5736f461d59c"
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    todelete = {
        "grado_ibfk_1": "grado",
        "asignatura_ibfk_2": "asignatura",
        "asignatura_ibfk_1": "asignatura",
        "perfilmodulolnk_ibfk_2": "perfilmodulolnk",
        "perfilmodulolnk_ibfk_1": "perfilmodulolnk",
        "auth_ibfk_1": "auth",
        "calendario_ibfk_1": "calendario",
        "evento_ibfk_1": "evento",
        "asignatura_ibfk_2": "asignatura",
        "asignatura_ibfk_1": "asignatura",
        "horario_ibfk_1": "horario",
        "evaluacion_ibfk_1": "evaluacion",
        "notificacioneventos_ibfk_1": "notificacioneventos",
        "qr_ibfk_1": "qr",
        "ausentismo_ibfk_1": "ausentismo",
        "user_ibfk_2": "user",
        "user_ibfk_3": "user",
        "user_ibfk_1": "user",
    }
    for key, tablename in todelete.items():
        try:
            op.drop_constraint(key, tablename, type_="foreignkey")
        except Exception:
            pass

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("correo")

    tables = [
        "qr",
        "perfil",
        "notificacioneventos",
        "calendario",
        "evaluacion",
        "asignatura",
        "perfilmodulolnk",
        "matricula",
        "auth",
        "grado",
        "module",
        "evento",
        "user",
        "ausentismo",
        "grupoetnico",
        "horario",
    ]
    for tablename in tables:
        try:
            op.drop_table(tablename)
        except Exception as e:
            print(f"-> {tablename}")
            print(e)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grupoetnico",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("grupo", mysql.VARCHAR(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "perfil",
        sa.Column(
            "nombreperfil",
            mysql.ENUM("SIN", "ESTUDIANTE", "DOCENTE", "ACUDIENTE", "ADMINISTRADOR"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nombreperfil"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "matricula",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "anio", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column(
            "periodo",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "grado",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("nombre", mysql.VARCHAR(length=50), nullable=False),
        sa.Column(
            "cupomaximo",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "matricula_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("comentariomatricula", mysql.VARCHAR(length=1200), nullable=False),
        sa.ForeignKeyConstraint(
            ["matricula_id"], ["matricula.id"], name="grado_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "module",
        sa.Column("modulename", mysql.VARCHAR(length=200), nullable=False),
        sa.PrimaryKeyConstraint("modulename"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "perfilmodulolnk",
        sa.Column(
            "perfil_id",
            mysql.ENUM("SIN", "ESTUDIANTE", "DOCENTE", "ACUDIENTE", "ADMINISTRADOR"),
            nullable=False,
        ),
        sa.Column("modulo_id", mysql.VARCHAR(length=200), nullable=False),
        sa.Column(
            "has_permision",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["modulo_id"], ["module.modulename"], name="perfilmodulolnk_ibfk_2"
        ),
        sa.ForeignKeyConstraint(
            ["perfil_id"], ["perfil.nombreperfil"], name="perfilmodulolnk_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("perfil_id", "modulo_id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("timestamp", mysql.DATETIME(), nullable=True),
        sa.Column("nombres", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("apellidos", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("numeroidentificacion", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("fechaNacimiento", sa.DATE(), nullable=False),
        sa.Column("rh", mysql.VARCHAR(length=3), nullable=False),
        sa.Column("telefonoContacto", mysql.VARCHAR(length=15), nullable=True),
        sa.Column("correo", mysql.VARCHAR(length=100), nullable=True),
        sa.Column(
            "perfil_nombre",
            mysql.ENUM("SIN", "ESTUDIANTE", "DOCENTE", "ACUDIENTE", "ADMINISTRADOR"),
            nullable=True,
        ),
        sa.Column(
            "grado_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("direccion", mysql.VARCHAR(length=500), nullable=False),
        sa.Column("telefono", mysql.VARCHAR(length=20), nullable=False),
        sa.Column(
            "grupoetnico_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["grado_id"], ["grado.id"], name="user_ibfk_2"),
        sa.ForeignKeyConstraint(
            ["grupoetnico_id"], ["grupoetnico.id"], name="user_ibfk_3"
        ),
        sa.ForeignKeyConstraint(
            ["perfil_nombre"], ["perfil.nombreperfil"], name="user_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("correo", ["correo"], unique=False)

    op.create_table(
        "auth",
        sa.Column(
            "usuario_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("timestamp", mysql.DATETIME(), nullable=True),
        sa.Column("hash", mysql.VARCHAR(length=100), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["user.id"], name="auth_ibfk_1"),
        sa.PrimaryKeyConstraint("usuario_id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "calendario",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("nombre", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("Desripcion", mysql.VARCHAR(length=1200), nullable=True),
        sa.Column(
            "propietario_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["propietario_id"], ["user.id"], name="calendario_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "evento",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("timestamp", mysql.DATETIME(), nullable=False),
        sa.Column("titulo", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("fechaHora", sa.DATE(), nullable=False),
        sa.Column("invitados", mysql.VARCHAR(length=1200), nullable=False),
        sa.Column("ubicacion", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("descripcion", mysql.VARCHAR(length=1200), nullable=False),
        sa.Column(
            "calendario_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calendario_id"], ["calendario.id"], name="evento_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "asignatura",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("nombre", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "grado_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "docente_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["docente_id"], ["user.id"], name="asignatura_ibfk_2"),
        sa.ForeignKeyConstraint(["grado_id"], ["grado.id"], name="asignatura_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "horario",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "diasemana",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "horaInicio",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "minutoInicio",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "horaFinal",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "minutoFinal",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "asignatura_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asignatura_id"], ["asignatura.id"], name="horario_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "evaluacion",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("fecha", sa.DATE(), nullable=False),
        sa.Column(
            "resultado",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("comentario", mysql.VARCHAR(length=800), nullable=False),
        sa.Column(
            "aprobado",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "periodo",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "evaluado_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["evaluado_id"], ["user.id"], name="evaluacion_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "notificacioneventos",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "tiempoantes",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("lineatiempo", mysql.VARCHAR(length=50), nullable=False),
        sa.Column(
            "evento_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"], ["evento.id"], name="notificacioneventos_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )

    op.create_table(
        "qr",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("timestamp", mysql.DATETIME(), nullable=True),
        sa.Column("code", mysql.VARCHAR(length=55), nullable=False),
        sa.Column(
            "usuario_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["user.id"], name="qr_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "ausentismo",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("fecha", sa.DATE(), nullable=False),
        sa.Column("timestamp", mysql.DATETIME(), nullable=False),
        sa.Column(
            "userausente_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("responsableRegistro", mysql.VARCHAR(length=200), nullable=False),
        sa.Column("comentario", mysql.VARCHAR(length=1200), nullable=False),
        sa.ForeignKeyConstraint(
            ["userausente_id"], ["user.id"], name="ausentismo_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
