"""empty message

Revision ID: 9d58b6dfab4a
Revises:
Create Date: 2024-07-25 04:10:51.928287

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9d58b6dfab4a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("perfiluserlnk")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "perfil_nombre",
                sa.Enum(
                    "SIN",
                    "ESTUDIANTE",
                    "DOCENTE",
                    "ACUDIENTE",
                    "ADMINISTRADOR",
                    name="perfilschool",
                ),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(None, "perfil", ["perfil_nombre"], ["nombreperfil"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("perfil_nombre")

    op.create_table(
        "perfiluserlnk",
        sa.Column(
            "perfil_id",
            mysql.ENUM("SIN", "ESTUDIANTE", "DOCENTE", "ACUDIENTE", "ADMINISTRADOR"),
            nullable=False,
        ),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["perfil_id"], ["perfil.nombreperfil"], name="perfiluserlnk_ibfk_1"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="perfiluserlnk_ibfk_2"),
        sa.PrimaryKeyConstraint("perfil_id", "user_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
